# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Rules = QtWidgets.QListWidget(self.centralwidget)
        self.Rules.setGeometry(QtCore.QRect(15, 20, 881, 491))
        self.Rules.setObjectName("Rules")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(920, 16, 231, 114))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonAdd = QtWidgets.QPushButton(self.groupBox)
        self.buttonAdd.setObjectName("buttonAdd")
        self.verticalLayout.addWidget(self.buttonAdd)
        self.buttonEdit = QtWidgets.QPushButton(self.groupBox)
        self.buttonEdit.setObjectName("buttonEdit")
        self.verticalLayout.addWidget(self.buttonEdit)
        self.buttonDelete = QtWidgets.QPushButton(self.groupBox)
        self.buttonDelete.setObjectName("buttonDelete")
        self.verticalLayout.addWidget(self.buttonDelete)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(920, 136, 231, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.premises = QtWidgets.QListWidget(self.groupBox_2)
        self.premises.setObjectName("premises")
        self.verticalLayout_2.addWidget(self.premises)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(920, 320, 231, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.condition = QtWidgets.QListWidget(self.groupBox_3)
        self.condition.setObjectName("condition")
        self.verticalLayout_3.addWidget(self.condition)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1165, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuKnowledge = QtWidgets.QMenu(self.menubar)
        self.menuKnowledge.setObjectName("menuKnowledge")
        self.menuRecommendation = QtWidgets.QMenu(self.menubar)
        self.menuRecommendation.setObjectName("menuRecommendation")
        self.menuSolution = QtWidgets.QMenu(self.menubar)
        self.menuSolution.setObjectName("menuSolution")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionVariables = QtWidgets.QAction(MainWindow)
        self.actionVariables.setObjectName("actionVariables")
        self.actionDomains = QtWidgets.QAction(MainWindow)
        self.actionDomains.setObjectName("actionDomains")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionViewOntology = QtWidgets.QAction(MainWindow)
        self.actionViewOntology.setObjectName("actionViewOntology")
        self.actionSolution = QtWidgets.QAction(MainWindow)
        self.actionSolution.setObjectName("actionSolution")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionFacts = QtWidgets.QAction(MainWindow)
        self.actionFacts.setObjectName("actionFacts")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuKnowledge.addAction(self.actionDomains)
        self.menuKnowledge.addAction(self.actionVariables)
        self.menuKnowledge.addAction(self.actionFacts)
        self.menuKnowledge.addSeparator()
        self.menuKnowledge.addAction(self.actionViewOntology)
        self.menuRecommendation.addAction(self.action)
        self.menuRecommendation.addSeparator()
        self.menuRecommendation.addAction(self.actionStart)
        self.menuSolution.addAction(self.actionSolution)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuKnowledge.menuAction())
        self.menubar.addAction(self.menuRecommendation.menuAction())
        self.menubar.addAction(self.menuSolution.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Действия"))
        self.buttonAdd.setText(_translate("MainWindow", "Добавить"))
        self.buttonEdit.setText(_translate("MainWindow", "Редактировать"))
        self.buttonDelete.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Условия"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Вывод"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuKnowledge.setTitle(_translate("MainWindow", "Знания"))
        self.menuRecommendation.setTitle(_translate("MainWindow", "Рекомендация"))
        self.menuSolution.setTitle(_translate("MainWindow", "Решение"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть ..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveAs.setText(_translate("MainWindow", "Сохранить как ..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionNew.setText(_translate("MainWindow", "Создать ..."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionVariables.setText(_translate("MainWindow", "Переменные"))
        self.actionVariables.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDomains.setText(_translate("MainWindow", "Домены"))
        self.actionDomains.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionStart.setText(_translate("MainWindow", "Начать"))
        self.actionStart.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionViewOntology.setText(_translate("MainWindow", "Просмотр отнологии"))
        self.actionViewOntology.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionSolution.setText(_translate("MainWindow", "Показать решение"))
        self.action.setText(_translate("MainWindow", "Цель консультации"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionFacts.setText(_translate("MainWindow", "Факты"))
